version: '3'
services:
  db:
    image: postgres
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'my_postgresql_password'
    volumes:
      - ${HOME}/Volumes/granola-db-data:/var/lib/postgresql/data
    networks:
      - backoffice
networks:
  backoffice:
